CREATE TABLE [dbo].[Sock](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Description] [varchar](500) NULL,
	[Colour] VARCHAR(9) NULL,
	[SizeId] INT NULL,
	[ThicknessId] INT NULL,
	[MaterialId] INT NULL,
	CONSTRAINT PK_SockId 
PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
